#!/usr/bin/python3

import sys

def factorize(n):
    factors = []
    for i in range(2, n//2 + 1):
        if n % i == 0:
            factors.append((i, n // i))
    return factors
if len(sys.argv) != 2:
    print("Incorrect path specification")
    sys.exit(1)

file_path = sys.argv[1]

try:
    with open(file_path, "r") as file:
        for line in file:
            number = int(line.strip())
            factor_pairs = factorize(number)
            for pair in factor_pairs:
                print(f"{number}={pair[0]}*{pair[1]}")
                        

except FileNotFoundError:
    print("File does not exist: ", file_path)

except Exception as e:
    print("An error has occured: ", e)
