#!/usr/bin/python3

import sys

if len(sys.argv) != 2:
    print("Incorrect path specification")
    sys.exit(1)

file_path = sys.argv[1]

try:
    with open(file_path, "r") as file:
        for line in file:
            line = int(line.strip())
            for first_number in range(1, line):
                for second_number in range(1, line):
                    if first_number * second_number == line:
                        print(f"{line}={second_number}*{first_number}")
                        break
                else:
                    continue
                break
                        

except FileNotFoundError:
    print("File does not exist: ", file_path)

except Exception as e:
    print("An error has occured: ", e)
